# SITE CONFIGURATION
title: Loyanne Cristine # your site title
author: loyannec # You :P
description: > # Meta description of Homepage
  I am a medical programmer, Data Science enthusiast who loves to share and exchange experiences,
  whether about career, medicine, technology or even life, being an immigrant and plants, many plants.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loyannec.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Loyannr Cristine
  links:
    - https://twitter.com/loyannec
    - https://www.linkedin.com/in/loyannec
    - https://github.com/loyannec

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Expat', link: '/expat'}
  - {name: 'Post-pt', link: '/post-pt'}

tagline: >
  a blog to share my experiences between personal and professional learning

hero_img: cliffs.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: loyanne.cristine@gmail.com # email for form submission

twitter_username: loyannec # replace with your_twitter_username or comment to remove link from footer
github_username:  loyannec # replace with your_github_username or comment to remove link from footer
instagram_username: loyannec # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: loyannec-com # to enable comments replace with your_disqus_shortname
  categories: [blog, project] # only show disqus for posts that have these categories

  google_analytics: UA-167856226-1
  google_tag_manager: UA-167856226-1 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
